modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv3"
issueTrackerURL = "https://github.com/MCTeamPotato/Fighto/issues"

[[mods]]
modId = "fighto"
version = "${version}"
displayName = "Fighto"
authors="Team Potato"
description = '''

'''